name: Test

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install go 1.21 as root
        run: sudo snap install go --channel=1.21/stable --classic
      - name: Run tests
        run: sudo su -c "/snap/bin/go test ebpf-detector/..."
      - name: Install llvm
        run: sudo apt-get update && sudo apt-get install -y llvm
      - name: Validate eBPF binaries are up to date
        run: |
          go generate ebpf-detector/...
          echo $(git diff)
          if (( $(git diff | wc -l) > 0 )); then exit 1; fi
